# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d54c4cbd64f5a60dde6ad89272a6db1f8f02d70f0dc535a2eb65057cdf7934cb6f537a02ee23a70d02fd4c3290f7c8a8fece0f08404cddd2951e50eb5d8b23e

test:
  secret_key_base: 38065a8960e14386330802af8972f7a9b5338738c2582fe4023035b4ad4cdd28ce274ee90e38362263183b2c0f55cf6fc3310c93f9d21b5147db7e77a313b16e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
